from __future__ import annotations

from abc import abstractmethod
from collections.abc import Callable
from typing import Any, ClassVar, Generic, Literal, TypeVar

import equinox as eqx
import jax
from diffrax._custom_types import RealScalarLike
from jaxtyping import Array

chart_order = int | Literal["exact"]
Geometry = TypeVar("Geometry", bound="Manifold[Any]")
CoeffField = Callable[[Array], Array]


class LocalChart(eqx.Module, Generic[Geometry]):
    order: RealScalarLike
    inverse_order: RealScalarLike

    @abstractmethod
    def apply(self, x: Array, a: Array, geometry: Geometry) -> Array:
        """Apply the chosen local chart at x for coefficients a."""
        ...

    def inverse_differential(
        self, x: Array, a: Array, b: Array, geometry: Geometry
    ) -> Array:
        """Apply the inverse differential of ``a -> apply(x, a, geometry)``."""
        raise NotImplementedError(
            f"{type(self).__name__} does not implement inverse_differential."
        )


class Manifold(eqx.Module, Generic[Geometry]):
    """Minimal manifold geometry backend for retraction-based integrators.

    This class contains only geometric primitives and does not contain solver
    logic. It is sufficient for retraction-based manifold Runge--Kutta schemes
    such as the current commutator-free solvers.
    """

    _chart_class: ClassVar[type[LocalChart]]
    chart: LocalChart[Geometry] | None = eqx.field(static=True, default=None)

    @property
    @abstractmethod
    def state_shape(self) -> tuple[int, ...]: ...

    @property
    @abstractmethod
    def coordinate_shape(self) -> tuple[int, ...]: ...

    @abstractmethod
    def trivialise(self, x: Array, v: Array) -> Array:
        """Convert ambient tangent vector v at state x to frame coordinates."""
        ...

    @abstractmethod
    def detrivialise(self, x: Array, a: Array) -> Array:
        """Convert frame coordinates a at state x to an ambient tangent vector."""
        ...

    @abstractmethod
    def frame_bracket(self, a: Array, b: Array) -> Array:
        """Bracket of constant frame-coordinate fields."""
        ...

    def check_state_shape(self, x: Array) -> None:
        if x.shape != self.state_shape:
            raise ValueError(
                f"{type(self).__name__} state must have shape {self.state_shape}; got {x.shape}."
            )

    def check_coordinate_shape(self, a: Array) -> None:
        if a.shape != self.coordinate_shape:
            raise ValueError(
                f"{type(self).__name__} coordinates must have shape {self.coordinate_shape}; got {a.shape}."
            )

    def apply_increment(self: Geometry, x: Array, a: Array) -> Array:
        """Apply the finite motion generated by frame coefficients a at x.

        Requires a local chart to have been selected by the solver.
        """
        self.check_state_shape(x)
        self.check_coordinate_shape(a)
        chart = self.chart
        if chart is None:
            raise TypeError(f"{type(self).__name__} requires a selected chart.")
        return chart.apply(x, a, self)

    def select_chart(
        self: Geometry, required_order: RealScalarLike
    ) -> LocalChart[Geometry]:
        """Choose a local chart based on the order required by the solver."""
        chart = self._chart_class(required_order)
        object.__setattr__(self, "chart", chart)
        return chart


def covariant_derivative(
    geometry: Manifold[Any], a_fn: CoeffField, b_fn: CoeffField, x: Array
) -> Array:
    a = a_fn(x)
    return jax.jvp(b_fn, (x,), (geometry.detrivialise(x, a),))[1]


def post_lie_bracket(
    geometry: Manifold[Any], a_fn: CoeffField, b_fn: CoeffField, x: Array
) -> Array:
    a, nabla_b_a = jax.jvp(a_fn, (x,), (geometry.detrivialise(x, b_fn(x)),))
    b, nabla_a_b = jax.jvp(b_fn, (x,), (geometry.detrivialise(x, a),))
    return nabla_a_b - nabla_b_a + geometry.frame_bracket(a, b)
