from __future__ import annotations

from abc import abstractmethod
from typing import Literal

import equinox as eqx
import jax
import jax.numpy as jnp
from diffrax._custom_types import RealScalarLike
from jaxtyping import Array

chart_order = int | Literal["exact"]


class LocalChart(eqx.Module):
    order: chart_order
    inverse_order: chart_order

    @abstractmethod
    def apply(self, x: Array, a: Array, geometry: "Manifold") -> Array:
        """Apply the chosen local chart at x for coefficients a."""
        ...

    def inverse_differential(
        self, x: Array, a: Array, b: Array, geometry: "Manifold"
    ) -> Array:
        """Apply the inverse differential of ``a -> apply(x, a, geometry)``.

        Generic AD fallback. ``to_frame(y, .)`` is linear in its second
        argument, so the Jacobian of ``c -> to_frame(y, apply(x, c))`` at
        ``c = a`` is the d x d restriction of the differential to the frame
        basis at ``y``. Subclasses with closed forms should override.
        """
        y = self.apply(x, a, geometry)

        def apply_in_frame(c):
            return geometry.to_frame(y, self.apply(x, c, geometry))

        jac = jnp.reshape(jax.jacfwd(apply_in_frame)(a), (b.size, a.size))
        coeffs = jnp.linalg.solve(jac, jnp.ravel(b))
        return jnp.reshape(coeffs, a.shape)


class Manifold(eqx.Module):
    """Minimal manifold geometry backend for retraction-based integrators.

    This class contains only geometric primitives and does not contain solver
    logic. It is sufficient for retraction-based manifold Runge--Kutta schemes
    such as the current commutator-free solvers.
    """

    chart: LocalChart | None = eqx.field(static=True, default=None)

    @abstractmethod
    def frame(self, x: Array) -> Array:
        """Return a local frame at x.

        Convention:
            shape = ambient_shape + (d,)
        where d = manifold dimension, and the last axis indexes frame vectors.
        """
        ...

    @abstractmethod
    def to_frame(self, x: Array, v: Array) -> Array:
        """Return coefficients a such that v = sum_i a_i E_i(x)."""
        ...

    @abstractmethod
    def from_frame(self, x: Array, a: Array) -> Array:
        """Return the tangent vector sum_i a_i E_i(x)."""
        ...

    @abstractmethod
    def retraction(self, x: Array, v: Array) -> Array:
        """Map a tangent vector v in T_xM back to M."""
        ...

    def apply_increment(self, x: Array, a: Array) -> Array:
        """Apply the finite motion generated by frame coefficients a at x.

        If a local chart model is attached, then it is used directly. Otherwise
        this retracts the tangent vector represented by ``a`` in the local frame.
        """
        if self.chart is not None:
            return self.chart.apply(x, a, self)
        return self.retraction(x, self.from_frame(x, a))

    @abstractmethod
    def select_chart(self, required_order: RealScalarLike) -> LocalChart:
        """Choose a local chart based on the order required by the solver."""
        ...
