from __future__ import annotations

from abc import abstractmethod
from typing import Literal

import equinox as eqx
from diffrax._custom_types import RealScalarLike
from jaxtyping import Array

flow_order = int | Literal["exact"]


class LocalFlow(eqx.Module):
    order: flow_order
    inverse_order: flow_order

    @abstractmethod
    def forward(self, x: Array, a: Array, geometry: "Manifold") -> Array:
        """Apply the chosen local finite motion at x for coefficients a."""
        ...

    def d_inverse(self, x: Array, y: Array, geometry: "Manifold") -> Array:
        """Apply the inverse differential of the local flow, when available."""
        raise NotImplementedError(
            f"{type(self).__name__} does not implement a differential inverse."
        )


class Manifold(eqx.Module):
    """Minimal manifold geometry backend for retraction-based integrators.

    This class contains only geometric primitives and does not contain solver
    logic. It is sufficient for retraction-based manifold Runge--Kutta schemes
    such as the current commutator-free solvers.
    """

    flow: LocalFlow | None = eqx.field(static=True, default=None)

    @abstractmethod
    def frame(self, x: Array) -> Array:
        """Return a local frame at x.

        Convention:
            shape = ambient_shape + (d,)
        where d = manifold dimension, and the last axis indexes frame vectors.
        """
        ...

    @abstractmethod
    def to_frame(self, x: Array, v: Array) -> Array:
        """Return coefficients a such that v = sum_i a_i E_i(x)."""
        ...

    @abstractmethod
    def from_frame(self, x: Array, a: Array) -> Array:
        """Return the tangent vector sum_i a_i E_i(x)."""
        ...

    @abstractmethod
    def retraction(self, x: Array, v: Array) -> Array:
        """Map a tangent vector v in T_xM back to M."""
        ...

    def frozen_flow(self, x: Array, a: Array) -> Array:
        """Apply the finite motion generated by frame coefficients a at x.

        If a local flow model is attached, then it is used directly. Otherwise
        this retracts the tangent vector represented by ``a`` in the local frame.
        """
        if self.flow is not None:
            return self.flow.forward(x, a, self)
        return self.retraction(x, self.from_frame(x, a))

    @abstractmethod
    def select_flow_method(self, required_order: RealScalarLike) -> LocalFlow:
        """Chooses an approximation to the flow based on the order required by the solver"""
        ...


class LieGroup(Manifold):
    """Lie-group geometry with a chosen chart for Lie-algebra integrators.

    The chart is understood as a local map tau from Lie-algebra coordinates to
    the group near the identity. For RKMK-style methods one needs the inverse
    of the left-trivialized chart differential at a.
    """

    @abstractmethod
    def chart_differential_inv(self, a: Array, b: Array) -> Array:
        """Apply the inverse left-trivialized chart differential at a to b."""
        ...
